using System.Collections.Generic;

namespace QuartzLauncher.Services;

public static class LogTranslator
{
    private static readonly Dictionary<string, string> CommonTranslations = new()
    {
        // 常见错误类型
        ["Error"] = "错误",
        ["Exception"] = "异常",
        ["Warning"] = "警告",
        ["Fatal"] = "致命",
        ["Critical"] = "严重",
        ["Failed"] = "失败",
        ["Cannot"] = "无法",
        ["Could not"] = "无法",
        ["Unable to"] = "无法",
        ["Not found"] = "未找到",
        ["Missing"] = "缺失",
        ["Null"] = "空值",
        ["Timeout"] = "超时",
        ["Connection"] = "连接",
        ["Memory"] = "内存",
        ["OutOfMemoryError"] = "内存溢出错误",
        ["Stack overflow"] = "堆栈溢出",
        ["File not found"] = "文件未找到",
        ["Access denied"] = "访问被拒绝",
        
        // Minecraft 相关
        ["inecraft"] = "inecraft",
        ["Server"] = "服务器",
        ["Client"] = "客户端",
        ["Mod"] = "模组",
        ["Plugin"] = "插件",
        ["Version"] = "版本",
        ["World"] = "世界",
        ["Chunk"] = "区块",
        ["Entity"] = "实体",
        ["Player"] = "玩家",
        ["Thread"] = "线程",
        ["Render"] = "渲染",
        ["OpenGL"] = "OpenGL",
        ["FML"] = "Forge",
        ["Fabric"] = "Fabric",
        ["Forge"] = "Forge",
        ["Paper"] = "Paper",
        ["Spigot"] = "Spigot",
        ["Bukkit"] = "Bukkit",
        
        // Java 相关
        ["java.lang"] = "Java类",
        ["java.util"] = "Java工具",
        ["java.io"] = "Java IO",
        ["java.net"] = "Java网络",
        ["at "] = "在 ",
        ["Caused by"] = "原因",
        ["at line"] = "在行",
        ["java.lang.OutOfMemoryError"] = "Java内存溢出错误",
        ["Java HotSpot"] = "Java HotSpot",
        
        // 常见解决方案关键词
        ["Solution"] = "解决方案",
        ["Fix"] = "修复",
        ["Fixes"] = "修复",
        ["Solution:"] = "解决方案：",
        ["Fix:"] = "修复：",
        ["How to fix"] = "如何修复",
        ["Steps to fix"] = "修复步骤",
        
        // 分析相关
        ["Analysis"] = "分析",
        ["Report"] = "报告",
        ["Diagnosis"] = "诊断",
        ["Issue"] = "问题",
        ["Problem"] = "问题",
        ["Cause"] = "原因",
        ["Reason"] = "原因",
        ["Summary"] = "摘要",
        ["Details"] = "详情",
        ["Log"] = "日志",
        ["Crash"] = "崩溃",
        ["Crash Report"] = "崩溃报告",
        
        // 日志级别
        ["INFO"] = "信息",
        ["DEBUG"] = "调试",
        ["TRACE"] = "追踪",
        
        // 常见错误消息
        ["java.lang.NullPointerException"] = "空指针异常",
        ["java.lang.ClassNotFoundException"] = "类未找到异常",
        ["java.lang.NoClassDefFoundError"] = "类定义未找到错误",
        ["java.lang.IllegalArgumentException"] = "非法参数异常",
        ["java.lang.IllegalStateException"] = "非法状态异常",
        ["java.lang.ArrayIndexOutOfBoundsException"] = "数组索引越界异常",
        ["java.lang.StringIndexOutOfBoundsException"] = "字符串索引越界异常",
        ["java.lang.NumberFormatException"] = "数字格式异常",
        ["java.lang.UnsupportedOperationException"] = "不支持的操作异常",
        ["java.util.ConcurrentModificationException"] = "并发修改异常",
        
        // 网络相关
        ["Connection refused"] = "连接被拒绝",
        ["Connection timed out"] = "连接超时",
        ["Connection reset"] = "连接重置",
        ["Network unreachable"] = "网络不可达",
        ["Host unreachable"] = "主机不可达",
        ["Port already in use"] = "端口已被占用",
        ["Address already in use"] = "地址已被占用",
        
        // 文件相关
        ["Permission denied"] = "权限被拒绝",
        ["Too many open files"] = "打开文件过多",
        ["No space left on device"] = "设备空间不足",
        ["Read-only file system"] = "只读文件系统",
        
        // 服务器相关
        ["server.properties"] = "server.properties",
        ["eula.txt"] = "eula.txt",
        ["banned-players.json"] = "banned-players.json",
        ["ops.json"] = "ops.json",
        ["whitelist.json"] = "whitelist.json",
        ["server-icon.png"] = "server-icon.png",
        ["libraries"] = "libraries",
        ["mods"] = "mods",
        ["plugins"] = "plugins",
        ["config"] = "config",
        ["logs"] = "logs",
        ["versions"] = "versions",
        ["saves"] = "saves",
        ["resourcepacks"] = "资源包",
        ["shaderpacks"] = "光影包",
        
        // 常见游戏术语
        ["TPS"] = "TPS（每秒ticks数）",
        ["RAM"] = "内存",
        ["CPU"] = "CPU",
        ["GPU"] = "显卡",
        ["FPS"] = "FPS（每秒帧数）",
        ["Ping"] = "延迟",
        ["Latency"] = "延迟",
        ["Bandwidth"] = "带宽",
        ["Tick"] = "Tick",
        ["Chunk loading"] = "区块加载",
        ["World generation"] = "世界生成",
        ["Redstone"] = "红石",
        ["Command"] = "命令",
        ["Permission"] = "权限",
        ["Ban"] = "封禁",
        ["Kick"] = "踢出",
        ["Whitelist"] = "白名单",
        ["OP"] = "管理员",
        
        // 分析报告结构
        ["## Summary"] = "## 摘要",
        ["## Analysis"] = "## 分析",
        ["## Report"] = "## 报告",
        ["## Diagnosis"] = "## 诊断",
        ["## Issues Found"] = "## 发现的问题",
        ["## Solutions"] = "## 解决方案",
        ["## Details"] = "## 详情",
        ["## Log Content"] = "## 日志内容",
        ["## Error Details"] = "## 错误详情",
        ["## Stack Trace"] = "## 堆栈跟踪",
        
        // 时间相关
        ["ago"] = "前",
        ["just now"] = "刚刚",
        ["seconds"] = "秒",
        ["minutes"] = "分钟",
        ["hours"] = "小时",
        ["days"] = "天",
        
        // 常见动词
        ["started"] = "已启动",
        ["stopped"] = "已停止",
        ["loaded"] = "已加载",
        ["unloaded"] = "已卸载",
        ["enabled"] = "已启用",
        ["disabled"] = "已禁用",
        ["initialized"] = "已初始化",
        ["completed"] = "已完成",
        ["finished"] = "已完成",
        ["done"] = "已完成",
        
        // 状态
        ["running"] = "运行中",
        ["stopped"] = "已停止",
        ["starting"] = "启动中",
        ["stopping"] = "停止中",
        ["loading"] = "加载中",
        ["unloading"] = "卸载中",
        
        // 连接状态
        ["online"] = "在线",
        ["offline"] = "离线",
        ["disconnected"] = "已断开",
        ["connected"] = "已连接",
        
        // MCDoctor 输出特有
        ["Crash detected"] = "检测到崩溃",
        ["No crash detected"] = "未检测到崩溃",
        ["Log analysis complete"] = "日志分析完成",
        ["Analysis complete"] = "分析完成",
        ["Report generated"] = "报告已生成",
        ["Diagnosis complete"] = "诊断完成",
        ["No issues found"] = "未发现任何问题",
        ["Issues found"] = "发现问题",
        ["Critical issues"] = "严重问题",
        ["Warnings found"] = "发现警告",
        ["Error found"] = "发现错误",
        ["Solution provided"] = "提供解决方案",
        ["Auto-fix available"] = "有自动修复方案",
        ["Manual fix required"] = "需要手动修复",
        ["Restart required"] = "需要重启",
        ["Configuration issue"] = "配置问题",
        ["Mod conflict"] = "模组冲突",
        ["Plugin conflict"] = "插件冲突",
        ["Version mismatch"] = "版本不匹配",
        ["Missing dependency"] = "缺失依赖",
        ["Outdated mod"] = "过时的模组",
        ["Outdated plugin"] = "过时的插件",
        ["Incompatible version"] = "不兼容版本",
        ["Corrupted file"] = "文件损坏",
        ["Invalid configuration"] = "无效配置",
        ["Insufficient memory"] = "内存不足",
        ["Heap space error"] = "堆空间错误",
        ["PermGen error"] = "永久代错误",
        ["Metaspace error"] = "元空间错误",
        
        // 整数相关
        ["Integer"] = "整数",
        ["Double"] = "浮点数",
        ["Float"] = "浮点数",
        ["Long"] = "长整数",
        ["Short"] = "短整数",
        ["Byte"] = "字节",
        ["Boolean"] = "布尔值",
        ["String"] = "字符串",
        ["Object"] = "对象",
        ["Array"] = "数组",
        ["List"] = "列表",
        ["Map"] = "映射",
        ["Set"] = "集合",
        ["Queue"] = "队列",
        ["Stack"] = "堆栈",
        ["Tree"] = "树",
        ["Graph"] = "图",
        
        // 网络状态码
        ["200 OK"] = "200 正常",
        ["301 Moved Permanently"] = "301 永久重定向",
        ["302 Found"] = "302 临时重定向",
        ["304 Not Modified"] = "304 未修改",
        ["400 Bad Request"] = "400 错误请求",
        ["401 Unauthorized"] = "401 未授权",
        ["403 Forbidden"] = "403 禁止访问",
        ["404 Not Found"] = "404 未找到",
        ["408 Request Timeout"] = "408 请求超时",
        ["429 Too Many Requests"] = "429 请求过多",
        ["500 Internal Server Error"] = "500 服务器内部错误",
        ["502 Bad Gateway"] = "502 错误网关",
        ["503 Service Unavailable"] = "503 服务不可用",
        ["504 Gateway Timeout"] = "504 网关超时",
        
        // MCDoctor 特有
        ["MCDoctor"] = "MCDoctor",
        ["AI Analysis"] = "AI 分析",
        ["Smart Fix"] = "智能修复",
        ["Auto Fix"] = "自动修复",
        ["Manual Fix"] = "手动修复",
        ["Advanced Analysis"] = "高级分析",
        ["Standard Analysis"] = "标准分析",
        ["Quick Analysis"] = "快速分析",
        ["Full Report"] = "完整报告",
        ["Summary Report"] = "摘要报告",
        ["Error Report"] = "错误报告",
        ["Crash Report"] = "崩溃报告",
        ["Log Upload"] = "日志上传",
        ["Log Content"] = "日志内容",
        ["Log File"] = "日志文件",
        ["Paste Log"] = "粘贴日志",
        ["Upload Log"] = "上传日志",
        ["Analyze Log"] = "分析日志",
        ["New Analysis"] = "新建分析",
        ["Save Report"] = "保存报告",
        ["Download Report"] = "下载报告",
        ["Copy Report"] = "复制报告",
        ["Share Report"] = "分享报告",
        ["Export Report"] = "导出报告",
        ["Print Report"] = "打印报告",
        ["Email Report"] = "邮件报告",
        ["Report History"] = "报告历史",
        ["Previous Analysis"] = "之前的分析",
        ["New Analysis"] = "新建分析",
        ["Start Over"] = "重新开始",
        ["Try Again"] = "重试",
        ["Go Back"] = "返回",
        ["Cancel"] = "取消",
        ["Close"] = "关闭",
        ["Save"] = "保存",
        ["Download"] = "下载",
        ["Upload"] = "上传",
        ["Copy"] = "复制",
        ["Paste"] = "粘贴",
        ["Delete"] = "删除",
        ["Remove"] = "移除",
        ["Add"] = "添加",
        ["Create"] = "创建",
        ["Edit"] = "编辑",
        ["Modify"] = "修改",
        ["Update"] = "更新",
        ["Refresh"] = "刷新",
        ["Reload"] = "重新加载",
        ["Restart"] = "重启",
        ["Stop"] = "停止",
        ["Start"] = "开始",
        ["Run"] = "运行",
        ["Execute"] = "执行",
        ["Process"] = "处理",
        ["Analyze"] = "分析",
        ["Diagnose"] = "诊断",
        ["Fix"] = "修复",
        ["Repair"] = "修复",
        ["Resolve"] = "解决",
        ["Solve"] = "解决",
        ["Troubleshoot"] = "故障排除",
        ["Debug"] = "调试",
        ["Test"] = "测试",
        ["Verify"] = "验证",
        ["Validate"] = "验证",
        ["Check"] = "检查",
        ["Inspect"] = "检查",
        ["Review"] = "审查",
        ["Audit"] = "审计",
        ["Scan"] = "扫描",
        ["Monitor"] = "监控",
        ["Track"] = "跟踪",
        ["Log"] = "记录",
        ["Record"] = "记录",
        ["Document"] = "记录",
        ["Note"] = "注意",
        ["Comment"] = "注释",
        ["Remark"] = "备注",
        ["Warning"] = "警告",
        ["Caution"] = "注意",
        ["Danger"] = "危险",
        ["Hazard"] = "危险",
        ["Risk"] = "风险",
        ["Threat"] = "威胁",
        ["Vulnerability"] = "漏洞",
        ["Exploit"] = "漏洞利用",
        ["Attack"] = "攻击",
        ["Breach"] = "入侵",
        ["Intrusion"] = "入侵",
        ["Compromise"] = "入侵",
        ["Incident"] = "事件",
        ["Outage"] = "中断",
        ["Downtime"] = "停机时间",
        ["Uptime"] = "运行时间",
        ["Availability"] = "可用性",
        ["Reliability"] = "可靠性",
        ["Performance"] = "性能",
        ["Scalability"] = "可扩展性",
        ["Stability"] = "稳定性",
        ["Consistency"] = "一致性",
        ["Integrity"] = "完整性",
        ["Security"] = "安全性",
        ["Privacy"] = "隐私",
        ["Confidentiality"] = "机密性",
        ["Authentication"] = "身份验证",
        ["Authorization"] = "授权",
        ["Access Control"] = "访问控制",
        ["Encryption"] = "加密",
        ["Decryption"] = "解密",
        ["Hashing"] = "哈希",
        ["Hash"] = "哈希",
        ["Checksum"] = "校验和",
        ["CRC"] = "CRC校验",
        ["MD5"] = "MD5哈希",
        ["SHA1"] = "SHA1哈希",
        ["SHA256"] = "SHA256哈希",
        ["Base64"] = "Base64编码",
        ["UTF8"] = "UTF-8编码",
        ["ASCII"] = "ASCII编码",
        ["Unicode"] = "Unicode编码",
        ["Charset"] = "字符集",
        ["Encoding"] = "编码",
        ["Decoding"] = "解码",
        ["Parse"] = "解析",
        ["Unparse"] = "反解析",
        ["Serialize"] = "序列化",
        ["Deserialize"] = "反序列化",
        ["Compress"] = "压缩",
        ["Decompress"] = "解压缩",
        ["Zip"] = "Zip压缩",
        ["Gzip"] = "Gzip压缩",
        ["Tar"] = "Tar打包",
        ["Archive"] = "归档",
        ["Extract"] = "解压",
        ["Backup"] = "备份",
        ["Restore"] = "恢复",
        ["Recovery"] = "恢复",
        ["Snapshot"] = "快照",
        ["Image"] = "镜像",
        ["Clone"] = "克隆",
        ["Copy"] = "复制",
        ["Duplicate"] = "复制",
        ["Replicate"] = "复制",
        ["Mirror"] = "镜像",
        ["Sync"] = "同步",
        ["Asynchronous"] = "异步",
        ["Synchronous"] = "同步",
        ["Concurrent"] = "并发",
        ["Parallel"] = "并行",
        ["Sequential"] = "顺序",
        ["Serial"] = "串行",
        ["Thread"] = "线程",
        ["Process"] = "进程",
        ["Task"] = "任务",
        ["Job"] = "作业",
        ["Worker"] = "工作线程",
        ["Pool"] = "池",
        ["Queue"] = "队列",
        ["Buffer"] = "缓冲区",
        ["Cache"] = "缓存",
        ["Memory"] = "内存",
        ["Storage"] = "存储",
        ["Disk"] = "磁盘",
        ["Drive"] = "驱动器",
        ["Volume"] = "卷",
        ["Partition"] = "分区",
        ["Filesystem"] = "文件系统",
        ["Directory"] = "目录",
        ["Folder"] = "文件夹",
        ["File"] = "文件",
        ["Path"] = "路径",
        ["Name"] = "名称",
        ["Extension"] = "扩展名",
        ["Suffix"] = "后缀",
        ["Prefix"] = "前缀",
        ["Format"] = "格式",
        ["Template"] = "模板",
        ["Pattern"] = "模式",
        ["Regular Expression"] = "正则表达式",
        ["Regex"] = "正则表达式",
        ["Wildcard"] = "通配符",
        ["Glob"] = "Glob模式",
        ["Search"] = "搜索",
        ["Find"] = "查找",
        ["Filter"] = "过滤",
        ["Sort"] = "排序",
        ["Order"] = "排序",
        ["Rank"] = "排名",
        ["Score"] = "评分",
        ["Rating"] = "评级",
        ["Level"] = "等级",
        ["Grade"] = "等级",
        ["Class"] = "类",
        ["Type"] = "类型",
        ["Kind"] = "种类",
        ["Category"] = "类别",
        ["Group"] = "组",
        ["Tag"] = "标签",
        ["Label"] = "标签",
        ["Attribute"] = "属性",
        ["Property"] = "属性",
        ["Field"] = "字段",
        ["Variable"] = "变量",
        ["Constant"] = "常量",
        ["Parameter"] = "参数",
        ["Argument"] = "参数",
        ["Value"] = "值",
        ["Key"] = "键",
        ["Index"] = "索引",
        ["Position"] = "位置",
        ["Offset"] = "偏移量",
        ["Length"] = "长度",
        ["Size"] = "大小",
        ["Count"] = "数量",
        ["Number"] = "数字",
        ["Quantity"] = "数量",
        ["Amount"] = "数量",
        ["Total"] = "总计",
        ["Sum"] = "总和",
        ["Average"] = "平均值",
        ["Mean"] = "平均值",
        ["Median"] = "中位数",
        ["Mode"] = "众数",
        ["Min"] = "最小值",
        ["Max"] = "最大值",
        ["Range"] = "范围",
        ["Span"] = "跨度",
        ["Width"] = "宽度",
        ["Height"] = "高度",
        ["Depth"] = "深度",
        ["Length"] = "长度",
        ["Breadth"] = "宽度",
        ["Thickness"] = "厚度",
        ["Diameter"] = "直径",
        ["Radius"] = "半径",
        ["Circumference"] = "周长",
        ["Area"] = "面积",
        ["Volume"] = "体积",
        ["Mass"] = "质量",
        ["Weight"] = "重量",
        ["Density"] = "密度",
        ["Temperature"] = "温度",
        ["Pressure"] = "压力",
        ["Force"] = "力",
        ["Energy"] = "能量",
        ["Power"] = "功率",
        ["Work"] = "功",
        ["Motion"] = "运动",
        ["Velocity"] = "速度",
        ["Acceleration"] = "加速度",
        ["Displacement"] = "位移",
        ["Direction"] = "方向",
        ["Angle"] = "角度",
        ["Rotation"] = "旋转",
        ["Torque"] = "扭矩",
        ["Momentum"] = "动量",
        ["Impulse"] = "冲量",
        ["Gravity"] = "重力",
        ["Friction"] = "摩擦力",
        ["Drag"] = "阻力",
        ["Buoyancy"] = "浮力",
        ["Elasticity"] = "弹性",
        ["Plasticity"] = "塑性",
        ["Viscosity"] = "粘度",
        ["Turbulence"] = "湍流",
        ["Laminar Flow"] = "层流",
        ["Reynolds Number"] = "雷诺数",
        ["Mach Number"] = "马赫数",
        ["Prandtl Number"] = "普朗特数",
        ["Nusselt Number"] = "努塞尔数",
        ["Rayleigh Number"] = "瑞利数",
        ["Grashof Number"] = "格拉晓夫数",
        ["Stanton Number"] = "斯坦顿数",
        ["Peclet Number"] = "佩克莱数",
        ["Schmidt Number"] = "施密特数",
        ["Lewis Number"] = "刘易斯数",
        ["Sherwood Number"] = "舍伍德数",
        ["Weber Number"] = "韦伯数",
        ["Froude Number"] = "弗劳德数",
        ["Strouhal Number"] = "斯特劳哈尔数",
        ["Cauchy Number"] = "柯西数",
        ["Euler Number"] = "欧拉数",
        ["Knudsen Number"] = "克努森数",
        ["Rossby Number"] = "罗斯贝数",
        ["Ekman Number"] = "埃克曼数",
        ["Richardson Number"] = "理查森数",
        ["Froude Number"] = "弗劳德数",
        ["Peclet Number"] = "佩克莱数",
        ["Reynolds Number"] = "雷诺数",
        ["Mach Number"] = "马赫数",
        ["Prandtl Number"] = "普朗特数",
        ["Nusselt Number"] = "努塞尔数",
        ["Rayleigh Number"] = "瑞利数",
        ["Grashof Number"] = "格拉晓夫数",
        ["Stanton Number"] = "斯坦顿数",
        ["Schmidt Number"] = "施密特数",
        ["Lewis Number"] = "刘易斯数",
        ["Sherwood Number"] = "舍伍德数",
        ["Weber Number"] = "韦伯数",
        ["Froude Number"] = "弗劳德数",
        ["Strouhal Number"] = "斯特劳哈尔数",
        ["Cauchy Number"] = "柯西数",
        ["Euler Number"] = "欧拉数",
        ["Knudsen Number"] = "克努森数",
        ["Rossby Number"] = "罗斯贝数",
        ["Ekman Number"] = "埃克曼数",
        ["Richardson Number"] = "理查森数",
    };

    public static string TranslateToChinese(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return text;

        var result = text;
        
        // 按长度从长到短排序替换，避免短词覆盖长词
        var sortedKeys = CommonTranslations.Keys.OrderByDescending(k => k.Length);
        
        foreach (var key in sortedKeys)
        {
            if (result.Contains(key))
            {
                result = result.Replace(key, CommonTranslations[key]);
            }
        }
        
        return result;
    }
}
